version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: intime
      POSTGRES_USER: intime
      POSTGRES_PASSWORD: intime
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: